spring:
  application:
    name: toy-back

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-autumn-rice-a10nv5gd-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_fzVoNZ8k2pdl
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: update

jwt:
  secret: NfWbUeYf3KxYFvD0c9N0+jEwTUzpYx3NbyX+PRT7c1pTCNy+xUJtbv9n==
  access-token-expiration: 900000    # 15분
  refresh-token-expiration: 604800000 # 7일
