spring:
  application:
    name: toy-back

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@oracle-tuning.c8if8vpxtdiy.ap-northeast-1.rds.amazonaws.com:1521/ORCL
    username: WINGSGAIAT
    password: WINGS_4172

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false

jwt:
  secret: NfWbUeYf3KxYFvD0c9N0+jEwTUzpYx3NbyX+PRT7c1pTCNy+xUJtbv9n==
  access-token-expiration: 900000    # 15분
  refresh-token-expiration: 604800000 # 7일
