spring:
  application:
    name: toy-back

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.18.25.141:5432/toyDatabase
    username: myuser
    password: myuser

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false

jwt:
  secret: NfWbUeYf3KxYFvD0c9N0+jEwTUzpYx3NbyX+PRT7c1pTCNy+xUJtbv9n==
  access-token-expiration: 900000    # 15분
  refresh-token-expiration: 604800000 # 7일
